I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1279, in script
    if(has_experience == True):
  File "game/script.rpy", line 1279, in <module>
    if(has_experience == True):
NameError: name 'has_experience' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1279, in script
    if(has_experience == True):
  File "D:\renpy-7.3.5-sdk\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "D:\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1279, in <module>
    if(has_experience == True):
NameError: name 'has_experience' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
XO KO 1.0
Mon Feb 10 16:48:13 2020
